### ISSUE TITLE
Making ParseHistoryForStartTTLs return the last TTL of each run

### ISSUE THREAD

**Issue by fatmai** [gallantlab/Eyetracking#2]
When the calibration starts at the end of the run this will be needed.

**Comment by candytaco** [comment]
https://github.com/gallantlab/Eyetracking/blob/master/EyetrackingUtilities.py#L94

I think this should do the job now but I have not yet verified it.

**Comment by candytaco** [comment]
ok `EyetrackingUtilities.ParseHistoryForEndTTLs` should work for your purposes now.
